services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: trendykiddos-backend

    restart: unless-stopped

    env_file:
      - .env

    environment:
      DJANGO_SETTINGS_MODULE: hardware_api.settings.prod

    ports:
      - "127.0.0.1:8003:8000"

    volumes:
      # Django source static directory
      - ./static:/app/static
      # Django collected static files
      - ./staticfiles:/app/staticfiles

      # User-uploaded files
      - ./media:/app/media

    networks:
      - nexlogs-internal-network

    command:
      [
        "gunicorn",
        "hardware_api.wsgi:application",
        "--bind",
        "0.0.0.0:8000",
        "--workers",
        "3",
        "--timeout",
        "120"
      ]

    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  nexlogs-internal-network:
    external: true
