# Generated by Django 6.0.1 on 2026-03-04 08:21

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='escrow_status',
            field=models.CharField(choices=[('awaiting_payment', 'Awaiting Payment'), ('held', 'Held'), ('released', 'Released')], default='awaiting_payment', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_ref',
            field=models.TextField(blank=True, help_text='Payment reference from payment system', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='release_code',
            field=models.TextField(blank=True, help_text='6-digit release code for delivery confirmation', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatusupdate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
