# Generated by Django 6.0.1 on 2026-03-09 14:20

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_escrow_status_order_payment_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='escrow_status',
            field=models.CharField(choices=[('awaiting_payment', 'Awaiting Payment'), ('held', 'Held'), ('released', 'Released'), ('non_escrow', 'Non-Escrow (COD)')], default='awaiting_payment', max_length=20),
        ),
    ]
