# Generated by Django 6.0.1 on 2026-04-22 09:06

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_escrow_status'),
        ('products', '0004_jobsite_procontractorprofile_productapproval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
