# Generated by Django 6.0.1 on 2026-06-19 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('STARTER', 'Starter'), ('BUSINESS', 'Business'), ('ENTERPRISE', 'Enterprise')], max_length=20, unique=True)),
                ('monthly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('onetime_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_users', models.PositiveIntegerField()),
                ('multi_branch', models.BooleanField(default=False)),
                ('barcode_support', models.BooleanField(default=False)),
                ('supplier_management', models.BooleanField(default=False)),
                ('stock_adjustments', models.BooleanField(default=False)),
                ('low_stock_alerts', models.BooleanField(default=False)),
                ('profit_loss_reports', models.BooleanField(default=False)),
                ('audit_logs', models.BooleanField(default=False)),
                ('api_access', models.BooleanField(default=False)),
                ('role_based_access', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='plans_name_idx'), models.Index(fields=['is_active'], name='plans_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200, unique=True)),
                ('subscription_status', models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='trial', max_length=20)),
                ('expiry_date', models.DateField()),
                ('max_users', models.PositiveIntegerField(help_text='Cached from plan for performance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='subscriptions.plan')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business_name'], name='org_name_idx'), models.Index(fields=['subscription_status'], name='org_status_idx'), models.Index(fields=['expiry_date'], name='org_expiry_idx'), models.Index(fields=['current_plan'], name='org_plan_idx')],
            },
        ),
    ]
