# Generated by Django 6.0.1 on 2026-06-19 02:27

from django.db import migrations
from django.utils import timezone
from decimal import Decimal


def create_plans_and_legacy_organization(apps, schema_editor):
    Plan = apps.get_model('subscriptions', 'Plan')
    Organization = apps.get_model('subscriptions', 'Organization')
    User = apps.get_model('accounts', 'User')
    
    # Create STARTER plan (both pricing options available)
    starter_plan = Plan.objects.create(
        name='STARTER',
        monthly_price=Decimal('29.00'),
        onetime_price=Decimal('290.00'),
        max_users=2,
        multi_branch=False,
        barcode_support=True,
        supplier_management=False,
        stock_adjustments=True,
        low_stock_alerts=True,
        profit_loss_reports=False,
        audit_logs=False,
        api_access=False,
        role_based_access=False,
        is_active=True
    )
    
    # Create BUSINESS plan (both pricing options available)
    business_plan = Plan.objects.create(
        name='BUSINESS',
        monthly_price=Decimal('99.00'),
        onetime_price=Decimal('990.00'),
        max_users=10,
        multi_branch=False,
        barcode_support=True,
        supplier_management=True,
        stock_adjustments=True,
        low_stock_alerts=True,
        profit_loss_reports=True,
        audit_logs=False,
        api_access=False,
        role_based_access=False,
        is_active=True
    )
    
    # Create ENTERPRISE plan (both pricing options available)
    enterprise_plan = Plan.objects.create(
        name='ENTERPRISE',
        monthly_price=Decimal('299.00'),
        onetime_price=Decimal('2990.00'),
        max_users=999999,  # Unlimited
        multi_branch=True,
        barcode_support=True,
        supplier_management=True,
        stock_adjustments=True,
        low_stock_alerts=True,
        profit_loss_reports=True,
        audit_logs=True,
        api_access=True,
        role_based_access=True,
        is_active=True
    )
    
    # Create Legacy Organization for existing users
    from datetime import timedelta
    expiry_date = timezone.now().date() + timedelta(days=30)
    
    legacy_org = Organization.objects.create(
        business_name='Legacy Organization',
        current_plan=starter_plan,
        subscription_status='active',
        expiry_date=expiry_date,
        max_users=starter_plan.max_users
    )
    
    # Migrate all existing users to Legacy Organization
    User.objects.filter(organization__isnull=True).update(organization=legacy_org)


def reverse_migration(apps, schema_editor):
    Plan = apps.get_model('subscriptions', 'Plan')
    Organization = apps.get_model('subscriptions', 'Organization')
    User = apps.get_model('accounts', 'User')
    
    # Remove organization from users
    User.objects.all().update(organization=None)
    
    # Delete Legacy Organization
    Organization.objects.filter(business_name='Legacy Organization').delete()
    
    # Delete plans
    Plan.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        ('accounts', '0008_user_organization'),
    ]

    operations = [
        migrations.RunPython(create_plans_and_legacy_organization, reverse_migration),
    ]
