# Generated by Django 6.0.1 on 2026-06-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20260619_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='pricing_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('onetime', 'One-time')], default='monthly', help_text='Selected pricing type for this organization', max_length=20),
        ),
        migrations.AddField(
            model_name='plan',
            name='pricing_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('onetime', 'One-time')], default='monthly', max_length=20),
        ),
    ]
