# Generated by Django 6.0.1 on 2026-06-19 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_organization_pricing_type_plan_pricing_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='pricing_type',
        ),
    ]
