# Generated by Django 6.0.1 on 2026-06-20 06:07

from django.db import migrations
from django.utils import timezone


def update_expiry_dates_to_monthly(apps, schema_editor):
    """Update existing organizations' expiry dates from yearly to monthly"""
    Organization = apps.get_model('subscriptions', 'Organization')
    
    from datetime import timedelta
    # Update all organizations to have monthly expiry dates (30 days from now)
    for org in Organization.objects.all():
        # Calculate new expiry date as 30 days from today
        new_expiry_date = timezone.now().date() + timedelta(days=30)
        org.expiry_date = new_expiry_date
        org.save()


def reverse_migration(apps, schema_editor):
    """Reverse the migration - set expiry dates back to yearly (365 days from now)"""
    Organization = apps.get_model('subscriptions', 'Organization')
    
    from datetime import timedelta
    # Revert all organizations to have yearly expiry dates (365 days from now)
    for org in Organization.objects.all():
        new_expiry_date = timezone.now().date() + timedelta(days=365)
        org.expiry_date = new_expiry_date
        org.save()


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_remove_plan_pricing_type'),
    ]

    operations = [
        migrations.RunPython(update_expiry_dates_to_monthly, reverse_migration),
    ]
