# Generated by Django 6.0.1 on 2026-06-22 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_auto_20260620_0607'),
    ]

    operations = [
    ]
