# Generated by Django 6.0.1 on 2026-06-22 09:24

from django.db import migrations


def update_starter_plan_features(apps, schema_editor):
    """Enable barcode_support, stock_adjustments, and low_stock_alerts for STARTER plan"""
    Plan = apps.get_model('subscriptions', 'Plan')
    
    # Update STARTER plan to enable additional features
    starter_plan = Plan.objects.filter(name='STARTER').first()
    if starter_plan:
        starter_plan.barcode_support = True
        starter_plan.stock_adjustments = True
        starter_plan.low_stock_alerts = True
        starter_plan.save()


def reverse_migration(apps, schema_editor):
    """Revert STARTER plan features to original state"""
    Plan = apps.get_model('subscriptions', 'Plan')
    
    # Revert STARTER plan features
    starter_plan = Plan.objects.filter(name='STARTER').first()
    if starter_plan:
        starter_plan.barcode_support = False
        starter_plan.stock_adjustments = False
        starter_plan.low_stock_alerts = False
        starter_plan.save()


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_auto_20260622_0919'),
    ]

    operations = [
        migrations.RunPython(update_starter_plan_features, reverse_migration),
    ]
