# Generated by Django 6.0.1 on 2026-05-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='user',
            name='staff_role',
            field=models.CharField(blank=True, choices=[('MANAGER', 'Manager'), ('CASHIER', 'Cashier'), ('INVENTORY_STAFF', 'Inventory Staff'), ('ADMIN', 'Admin')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('PRO_CONTRACTOR', 'Pro-Contractor'), ('STAFF', 'Staff')], default='CUSTOMER', max_length=32),
        ),
    ]
