# Generated by Django 6.0.1 on 2026-05-28 10:20

from django.db import migrations


def migrate_admin_users(apps, schema_editor):
    """Migrate existing ADMIN and SUPERUSER users to STAFF role with staff_role=ADMIN"""
    User = apps.get_model('accounts', 'User')
    
    # Migrate users with old ADMIN role to STAFF with staff_role=ADMIN
    User.objects.filter(role='ADMIN').update(role='STAFF', staff_role='ADMIN')
    
    # Migrate users with SUPERUSER role to STAFF with staff_role=ADMIN
    # SUPERUSER was likely a custom value, treat it as admin
    User.objects.filter(role='SUPERUSER').update(role='STAFF', staff_role='ADMIN')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_is_staff_user_staff_role_alter_user_role'),
    ]

    operations = [
        migrations.RunPython(migrate_admin_users, migrations.RunPython.noop),
    ]
