# Generated by Django 6.0.1 on 2026-06-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_migrate_admin_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='store_id',
            field=models.CharField(blank=True, default='main', help_text='Store ID for STAFF users', max_length=100, null=True),
        ),
    ]
