# Generated by Django 6.0.1 on 2026-04-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_jobsite_procontractorprofile_productapproval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalspecification',
            name='spec_type',
            field=models.CharField(choices=[('voltage', 'Voltage'), ('material', 'Material'), ('size', 'Size'), ('capacity', 'Capacity'), ('power', 'Power'), ('weight', 'Weight'), ('dimensions', 'Dimensions'), ('technical', 'Technical'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
