# Generated by Django 6.0.1 on 2026-04-30 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_technicalspecification_spec_type'),
        ('products', 'add_performance_indexes'),
    ]

    operations = [
    ]
