# Generated by Django 6.0.1 on 2026-05-04 12:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_merge_20260430_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_quantity', models.IntegerField(help_text='Previous stock quantity')),
                ('new_quantity', models.IntegerField(help_text='New stock quantity')),
                ('change_amount', models.IntegerField(help_text='Quantity change (+ or -)')),
                ('source', models.CharField(choices=[('ecommerce', 'E-commerce'), ('pos', 'POS'), ('admin', 'Admin')], help_text='Source of stock change', max_length=20)),
                ('store_id', models.CharField(default='main', help_text='Store/terminal identifier', max_length=50)),
                ('operator', models.CharField(help_text='User who made the change', max_length=100)),
                ('device_id', models.CharField(blank=True, help_text='POS device identifier', max_length=100, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('conflict', 'Conflict')], default='pending', help_text='Synchronization status', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the change occurred')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When sync completed', null=True)),
                ('conflict_reason', models.TextField(blank=True, help_text='Reason for conflict if any', null=True)),
                ('resolved_by', models.CharField(blank=True, help_text='Who resolved the conflict', max_length=100, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='last_pos_sync',
            field=models.DateTimeField(blank=True, help_text='Last time POS synced stock', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pos_stock_quantity',
            field=models.IntegerField(default=0, help_text='Stock quantity from POS system'),
        ),
        migrations.AddField(
            model_name='product',
            name='pos_store_id',
            field=models.CharField(default='main', help_text='POS store identifier', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last time stock was updated'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_sync_version',
            field=models.IntegerField(default=0, help_text='Version number for stock sync conflicts'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_update_source',
            field=models.CharField(choices=[('ecommerce', 'E-commerce'), ('pos', 'POS'), ('admin', 'Admin')], default='admin', help_text='Source of last stock update', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_updated_by',
            field=models.CharField(blank=True, help_text='User who last updated stock', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['pos_stock_quantity', 'last_pos_sync'], name='products_pos_sync_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['pos_store_id', 'stock_sync_version'], name='products_pos_store_version_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock_update_source', 'stock_last_updated'], name='products_stock_source_time_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode', 'is_active'], name='products_barcode_active_idx'),
        ),
        migrations.AddField(
            model_name='stocksynclog',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_sync_logs', to='products.product'),
        ),
        migrations.AddIndex(
            model_name='stocksynclog',
            index=models.Index(fields=['product', 'timestamp'], name='stock_sync_product_time_idx'),
        ),
        migrations.AddIndex(
            model_name='stocksynclog',
            index=models.Index(fields=['source', 'timestamp'], name='stock_sync_source_time_idx'),
        ),
        migrations.AddIndex(
            model_name='stocksynclog',
            index=models.Index(fields=['store_id', 'timestamp'], name='stock_sync_store_time_idx'),
        ),
        migrations.AddIndex(
            model_name='stocksynclog',
            index=models.Index(fields=['sync_status', 'timestamp'], name='stock_sync_status_time_idx'),
        ),
        migrations.AddIndex(
            model_name='stocksynclog',
            index=models.Index(fields=['timestamp'], name='stock_sync_timestamp_idx'),
        ),
    ]
