# Generated by Django 6.0.1 on 2026-06-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_stocksynclog_product_last_pos_sync_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Optional expiry date for the product', null=True),
        ),
    ]
